apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.name }}

spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.registry }}/giantswarm/{{ .Values.image.name }}:{{ .Values.image.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8000
          volumeMounts:
          - mountPath: /var/cache/nginx
            name: cache-volume
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
      - name: cache-volume
        emptyDir: {}
      serviceAccount: {{ .Values.name }}
      serviceAccountName: {{ .Values.name }}
