name: api-spec-app
namespace: docs
image:
  registry: gsoci.azurecr.io
  name: api-spec
  tag: "[[.Version]]"
  sha: "[[.SHA]]"
resources:
  requests:
    cpu: 5m
    memory: 5M
  limits:
    cpu: 50m
    memory: 20M
global:
  podSecurityStandards:
    enforced: false
